# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git' 

target 'SwipeDownClose' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxGesture'
  pod 'Kingfisher'
  pod 'Alamofire'

  # Pods for SwipeDownClose

  target 'SwipeDownCloseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
